version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTG-RES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data:/data
    expose:
      - "6379"

  huey_worker:
    build: .
    command: python manage.py run_huey
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SERVER_ENV: ${SERVER_ENV}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_EMAIL_ADDR: ${EMAIL_EMAIL_ADDR}
      RAVEN_DSN: ${RAVEN_DSN}
      REDIS_URL: ${REDIS_URL}
    volumes:
      - .:/PawPrints
    depends_on:
      - redis
      - postgres

  web:
    build: .
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 pawprints.asgi:application"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SERVER_ENV: ${SERVER_ENV}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_EMAIL_ADDR: ${EMAIL_EMAIL_ADDR}
      RAVEN_DSN: ${RAVEN_DSN}
      REDIS_URL: ${REDIS_URL}
      GOOGLE_ID: ${GOOGLE_ANALYTICS}
    volumes:
      - .:/PawPrints
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres

volumes:
  postgres-data:
  redis-data:
